### ISSUE TITLE
计划扫描后没有自动下载字幕

### ISSUE THREAD

**Issue by NEOherozzz** [ChineseSubFinder/ChineseSubFinder#578]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: vx.x.x
>v0.45.0
> 环境: docker or Window or Linux or MAC
>docker
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？

> 描述一下你遇到的问题
扫描后没有自动下载没有字幕的电影和电视剧

## 你的问题弄重现嘛？

> 能够重新，不能够重现
能够重现

## 你期望的结果

> 描述以下你期望的结果
在扫描后自动添加没有字幕的项目到下载队列

## 给出当前程序的配置文件

> /volume1/docker/chinesesubfinder/config:/config 下，ChineseSubFinderSettings.json，记得把你的用户名、密码、Emby API 敏感信息删除
>
> 可以复制上面的配置，使用类似在线 json 格式化的工具进行一次处理，方便阅读，[JSON 在线解析及格式化验证 - JSON.cn](https://www.json.cn/#)

```json
{
    "SpeedDevMode": false,
    "user_info": {
        "username": "xxx",
        "password": "xxx"
    },
    "common_settings": {
        "interval_or_assign_or_custom": 2,
        "scan_interval": "35 21 * * *",
        "threads": 6,
        "run_scan_at_start_up": false,
        "movie_paths": [
            "/media/Emby/movies",
            "/media/Emby_remote/movies"
        ],
        "series_paths": [
            "/media/Emby/tv_shows",
            "/media/Emby_remote/tv_shows"
        ],
        "local_static_file_port": "19037"
    },
    "subtitle_sources": {
        "assrt_settings": {
            "enabled": true,
            "token": "xxx"
        }
    },
    "advanced_settings": {
        "proxy_settings": {
            "use_proxy": false,
            "use_which_proxy_protocol": "http",
            "local_http_proxy_server_port": "19036",
            "input_proxy_address": "127.0.0.1",
            "input_proxy_port": "10809",
            "need_pwd": false,
            "input_proxy_username": "",
            "input_proxy_password": ""
        },
        "tmdb_api_settings": {
            "enable": true,
            "api_key": "xxx"
        },
        "debug_mode": false,
        "save_full_season_tmp_subtitles": false,
        "sub_type_priority": 0,
        "sub_name_formatter": 0,
        "save_multi_sub": false,
        "custom_video_exts": [],
        "fix_time_line": false,
        "topic": 1,
        "suppliers_settings": {
            "csf": {
                "name": "csf",
                "root_url": "haha",
                "search_url": "haha",
                "daily_download_limit": -1
            },
            "xunlei": {
                "name": "xunlei",
                "root_url": "http://sub.xmp.sandai.net:8000/subxl/%s.json",
                "search_url": "",
                "daily_download_limit": -1
            },
            "shooter": {
                "name": "shooter",
                "root_url": "https://www.shooter.cn/api/subapi.php",
                "search_url": "",
                "daily_download_limit": -1
            },
            "subhd": {
                "name": "subhd",
                "root_url": "https://subhd.tv",
                "search_url": "/search/%s",
                "daily_download_limit": 20
            },
            "zimuku": {
                "name": "zimuku",
                "root_url": "https://zimuku.org",
                "search_url": "/search?q=%s",
                "daily_download_limit": 20
            },
            "assrt": {
                "name": "assrt",
                "root_url": "https://api.assrt.net/v1",
                "search_url": "",
                "daily_download_limit": -1
            },
            "a4k": {
                "name": "a4k",
                "root_url": "https://www.a4k.net",
                "search_url": "/search?term=",
                "daily_download_limit": -1
            }
        },
        "scan_logic": {
            "skip_chinese_movie": false,
            "skip_chinese_series": false
        },
        "task_queue": {
            "max_retry_times": 3,
            "one_job_time_out": 300,
            "interval": 10,
            "expiration_time": 90,
            "download_sub_during_x_days": 7,
            "one_sub_download_interval": 12,
            "check_pulic_ip_target_site": ""
        },
        "download_file_cache": {
            "ttl": 4320,
            "unit": "hour"
        }
    },
    "emby_settings": {
        "enable": true,
        "address_url": "http://xxx:8096",
        "api_key": "xxx",
        "max_request_video_number": 3000,
        "skip_watched": false,
        "movie_paths_mapping": {
            "/media/Emby/movies": "",
            "/media/Emby_remote/movies": ""
        },
        "series_paths_mapping": {
            "/media/Emby/tv_shows": "",
            "/media/Emby_remote/tv_shows": ""
        },
        "auto_or_manual": true,
        "threads": 6
    },
    "developer_settings": {
        "enable": false,
        "bark_server_address": ""
    },
    "timeline_fixer_settings": {
        "max_offset_time": 700,
        "min_offset": 0.2
    },
    "experimental_function": {
        "auto_change_sub_encode": {
            "enable": true,
            "des_encode_type": 0
        },
        "chs_cht_changer": {
            "enable": true,
            "des_chinese_language_type": 0
        },
        "remote_chrome_settings": {
            "enable": false,
            "remote_docker_url": "",
            "remote_adblock_path": "",
            "remote_user_data_dir": ""
        },
        "api_key_settings": {
            "enabled": false,
            "key": ""
        },
        "local_chrome_settings": {
            "enabled": false,
            "local_chrome_exe_f_path": ""
        },
        "share_sub_settings": {
            "share_sub_enabled": false
        },
        "extend_log": {
            "SysLog": {
                "enable": false,
                "network": "",
                "address": "",
                "priority": 0,
                "tag": ""
            }
        }
    }
}
```

## 如果是使用 Docker，请给出对应的配置信息

> 比如 Docker-Compose 信息，如果是其他方式使用忽略

```yaml
version: "3"
services:
  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest
    volumes:
      - /mnt/user/appdata/chineseSubFinder/config:/config  # 冒号左边请修改为你想在主机上保存配置、日志等文件的路径
      - /mnt/user/media:/media    # 请修改为你的媒体目录，冒号右边可以改成你方便记忆的目录，多个媒体目录需要分别映射进来
      - /mnt/user/appdata/chineseSubFinder/browser:/root/.cache/rod/browser    # 容器重启后无需再次下载 chrome，除非 go-rod 更新
      - /mnt/user/downloads:/mnt/user/downloads
      - /mnt/user/remote:/mnt/user/remote
    environment:
      - PUID=1000         # uid
      - PGID=100          # gid
      - PERMS=false        # 是否重设/media权限
      - TZ=Asia/Shanghai  # 时区
      - UMASK=022         # 权限掩码
    network_mode: bridge
    hostname: chinesesubfinder
    container_name: chinesesubfinder
    ports:
      - 19035:19035  # 从0.20.0版本开始，通过webui来设置
      - 19037:19037  # webui 的视频列表读取图片用，务必设置不要暴露到外网
    logging:
        driver: "json-file"
        options:
          max-size: "100m" # 限制docker控制台日志大小，可自行调整
```

## 给出媒体文件夹的目录结构

> 首先你需要去看主页的部署教程，确认你目录结构是规范的，如果你觉得没问题，那么请除非目录结构截图

> 是否看过对应的目录结构要求文档？
是
- [电影的推荐目录结构](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E7%94%B5%E5%BD%B1%E5%92%8C%E8%BF%9E%E7%BB%AD%E5%89%A7%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E7%A4%BA%E4%BE%8B.md)
- [连续剧目录结构要求](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E8%BF%9E%E7%BB%AD%E5%89%A7%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E8%A6%81%E6%B1%82.md)

## 请给出当次问题的完整日志

> 日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。
[INFO]: 2022-11-29 21:35:00 - scanVideoProcessAdd2DownloadQueue Start: 2022-11-29 21:35:00
[INFO]: 2022-11-29 21:35:00 - ------------------------------------
[INFO]: 2022-11-29 21:35:00 - Video Scan Started...
[INFO]: 2022-11-29 21:35:00 - ScanNormalMovieAndSeries Start...
[INFO]: 2022-11-29 21:35:00 -  --------------------------------------------------
[INFO]: 2022-11-29 21:35:00 - MatchedVideoFileFromDirs Start...
[INFO]: 2022-11-29 21:35:00 - ------------------------------------------
[INFO]: 2022-11-29 21:35:00 - GetSeriesListFromDirs Start...
[INFO]: 2022-11-29 21:35:00 - GetSeriesListFromDirs End
[INFO]: 2022-11-29 21:35:00 - ------------------------------------------
[INFO]: 2022-11-29 21:35:00 - MatchedVideoFileFromDirs End
[INFO]: 2022-11-29 21:35:00 -  --------------------------------------------------
[INFO]: 2022-11-29 21:35:00 - updateLocalVideoCacheInfo 2 /media/Emby/movies/猎凶风河谷 (2017)/猎凶风河谷 (2017) 1080p AC3.mkv
... ...
[INFO]: 2022-11-29 21:35:03 - updateLocalVideoCacheInfo 5 /media/Emby_remote/tv_shows/风骚律师 (2015)
[INFO]: 2022-11-29 21:35:04 - ScanNormalMovieAndSeries End
[INFO]: 2022-11-29 21:35:04 - ScanEmbyMovieAndSeries Start...
[INFO]: 2022-11-29 21:35:04 - Not Forced Scan And DownSub
[INFO]: 2022-11-29 21:35:04 - Movie Sub Dl From Emby API...
[INFO]: 2022-11-29 21:35:04 - Refresh Emby Sub List Start...
[INFO]: 2022-11-29 21:35:04 - Refresh Emby Sub List Success
[INFO]: 2022-11-29 21:35:04 - getUpdateVideoListFromEmby Start...
[INFO]: 2022-11-29 21:35:04 - getUpdateVideoListFromEmby End
[INFO]: 2022-11-29 21:35:04 - ScanEmbyMovieAndSeries End
[INFO]: 2022-11-29 21:35:04 - VideoScanAndRefreshHelper finished, cost: 0.07997502025 min
[INFO]: 2022-11-29 21:35:04 - Video Scan End
[INFO]: 2022-11-29 21:35:04 - ------------------------------------
后续就没有了
> /volume1/docker/chinesesubfinder/config:/config 下，Logs 中
