### ISSUE TITLE
视频文件是软链接时，无法启动搜索、下载字幕的过程

### ISSUE THREAD

**Issue by neutralevil** [ChineseSubFinder/ChineseSubFinder#594]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.45.1
>
> 环境: docker

## 你遇到什么问题了？

以下问题出现在视频文件是软链接时，如果手工把软链接替换为复制过来的实际文件，则一切正常。软链接是nas-tools整理功能自动生成的：
1. 在“库”里面点击电影下面的放大镜，关键字列表一直空白
2. 点击下载字幕，不一会下载队列中刚加入的任务被删除， 输出会显示（.mp4那个实际上是蓝光原盘）：
```
[INFO]: 2022-12-23 22:44:40 - /media/Movie/外语电影/阿凡达 (2009)/阿凡达 (2009).mkv is missing, Delete This Job
[INFO]: 2022-12-23 22:44:55 - /media/Movie/外语电影/变形金刚4：绝迹重生 (2014)/变形金刚4：绝迹重生 (2014).mp4 is missing, Delete This Job
```

## 你的问题弄重现嘛？

> 能够重新

## 你期望的结果

> 视频文件是软链接时也能正常工作

## 给出当前程序的配置文件

```json
{
    "SpeedDevMode": false,
    "user_info": {
        "username": "",
        "password": ""
    },
    "common_settings": {
        "interval_or_assign_or_custom": 0,
        "scan_interval": "@every 6h",
        "threads": 3,
        "run_scan_at_start_up": false,
        "movie_paths": [
            "/media/Movie"
        ],
        "series_paths": [
            "/media/TV"
        ],
        "local_static_file_port": "19037"
    },
    "subtitle_sources": {
        "assrt_settings": {
            "enabled": false,
            "token": ""
        }
    },
    "advanced_settings": {
        "proxy_settings": {
            "use_proxy": false,
            "use_which_proxy_protocol": "http",
            "local_http_proxy_server_port": "",
            "input_proxy_address": "",
            "input_proxy_port": "",
            "need_pwd": false,
            "input_proxy_username": "",
            "input_proxy_password": ""
        },
        "tmdb_api_settings": {
            "enable": true,
            "api_key": ""
        },
        "debug_mode": false,
        "save_full_season_tmp_subtitles": false,
        "sub_type_priority": 0,
        "sub_name_formatter": 1,
        "save_multi_sub": false,
        "custom_video_exts": [],
        "fix_time_line": true,
        "topic": 1,
        "suppliers_settings": {
            "csf": {
                "name": "csf",
                "root_url": "haha",
                "search_url": "haha",
                "daily_download_limit": -1
            },
            "xunlei": {
                "name": "xunlei",
                "root_url": "http://sub.xmp.sandai.net:8000/subxl/%s.json",
                "search_url": "",
                "daily_download_limit": -1
            },
            "shooter": {
                "name": "shooter",
                "root_url": "https://www.shooter.cn/api/subapi.php",
                "search_url": "",
                "daily_download_limit": -1
            },
            "subhd": {
                "name": "subhd",
                "root_url": "https://subhd.tv",
                "search_url": "/search/%s",
                "daily_download_limit": 20
            },
            "zimuku": {
                "name": "zimuku",
                "root_url": "https://zimuku.org",
                "search_url": "/search?q=%s",
                "daily_download_limit": 20
            },
            "assrt": {
                "name": "assrt",
                "root_url": "https://api.assrt.net/v1",
                "search_url": "",
                "daily_download_limit": -1
            },
            "a4k": {
                "name": "a4k",
                "root_url": "https://www.a4k.net",
                "search_url": "/search?term=",
                "daily_download_limit": -1
            }
        },
        "scan_logic": {
            "skip_chinese_movie": false,
            "skip_chinese_series": false
        },
        "task_queue": {
            "max_retry_times": 3,
            "one_job_time_out": 300,
            "interval": 10,
            "expiration_time": 90,
            "download_sub_during_x_days": 7,
            "one_sub_download_interval": 12,
            "check_pulic_ip_target_site": ""
        },
        "download_file_cache": {
            "ttl": 4320,
            "unit": "hour"
        }
    },
    "emby_settings": {
        "enable": false,
        "address_url": "",
        "api_key": "",
        "max_request_video_number": 500,
        "skip_watched": false,
        "movie_paths_mapping": {
            "/media/Movie": ""
        },
        "series_paths_mapping": {
            "/media/TV": ""
        },
        "auto_or_manual": true,
        "threads": 3
    },
    "developer_settings": {
        "enable": false,
        "bark_server_address": ""
    },
    "timeline_fixer_settings": {
        "max_offset_time": 700,
        "min_offset": 0.2
    },
    "experimental_function": {
        "auto_change_sub_encode": {
            "enable": false,
            "des_encode_type": 0
        },
        "chs_cht_changer": {
            "enable": false,
            "des_chinese_language_type": 0
        },
        "remote_chrome_settings": {
            "enable": false,
            "remote_docker_url": "",
            "remote_adblock_path": "",
            "remote_user_data_dir": ""
        },
        "api_key_settings": {
            "enabled": true,
            "key": ""
       },
        "local_chrome_settings": {
            "enabled": false,
            "local_chrome_exe_f_path": ""
        },
        "share_sub_settings": {
            "share_sub_enabled": true
        },
        "extend_log": {
            "SysLog": {
                "enable": false,
                "network": "",
                "address": "",
                "priority": 0,
                "tag": ""
            }
        }
    }
}
```

## 如果是使用 Docker，请给出对应的配置信息

```yaml
 chinesesubfinder:
    hostname: chinesesubfinder
    container_name: chinesesubfinder
    restart: unless-stopped
    network_mode: bridge
    image: allanpk716/chinesesubfinder:latest
    volumes:
      - /share/Container/chinesesubfinder/config:/config  # 冒号左边请修改为你想在主机上保存配置、日志等文件的路径
      - /share/Container/chinesesubfinder/cache:/cache  # 冒号左边请修改为你想在主机上保存配置、日志等文件的路径
      - /share/Media:/media    # 请修改为你的媒体目录，冒号右边可以改成你方便记忆的目录，多个媒体目录需要分别映射进来
      - /share/Container/chinesesubfinder/browser:/root/.cache/rod/browser    # 容器重启后无需再次下载 chrome，除非 go-rod 更新
    environment:
        PUID: 1000
        PGID: 100
        UMASK: 022
        TZ: Asia/Shanghai
        # PERMS: true        # 是否重设/media权限
    ports:
      - 19035:19035  # 从0.20.0版本开始，通过webui来设置
      - 19037:19037  # webui 的视频列表读取图片用，务必设置不要暴露到外网
    logging:
        driver: "json-file"
        options:
          max-size: "100m" # 限制docker控制台日志大小，可自行调整
```

## 给出媒体文件夹的目录结构

> 首先你需要去看主页的部署教程，确认你目录结构是规范的，如果你觉得没问题，那么请除非目录结构截图

> 是否看过对应的目录结构要求文档？

- [电影的推荐目录结构](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E7%94%B5%E5%BD%B1%E5%92%8C%E8%BF%9E%E7%BB%AD%E5%89%A7%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E7%A4%BA%E4%BE%8B.md)
- [连续剧目录结构要求](https://github.com/allanpk716/ChineseSubFinder/blob/docs/DesignFile/%E8%BF%9E%E7%BB%AD%E5%89%A7%E7%9B%AE%E5%BD%95%E7%BB%93%E6%9E%84%E8%A6%81%E6%B1%82.md)

## 请给出当次问题的完整日志

> 日志在程序的 Logs 目录下，如果你用的是 docker ，那么需要你映射出来。

> /volume1/docker/chinesesubfinder/config:/config 下，Logs 中
