### ISSUE TITLE
个别连续剧不显示第几季

### ISSUE THREAD

**Issue by tabris233** [ChineseSubFinder/ChineseSubFinder#650]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v0.50.3 Lite
>
> 环境: docker

## 你遇到什么问题了？

个别连续剧不显示第几季，导致不能正常上传本地字幕文件。

## 你的问题弄重现嘛？

能够稳定重现

## 你期望的结果

识别该连续剧的`第几季`信息，能够正常上传字幕。

## 给出当前程序的配置文件

<details><summary>展开/收起</summary>

```json
{
    "SpeedDevMode": false,
    "user_info": {
        "username": "xxxxxx",
        "password": "xxxxxx"
    },
    "common_settings": {
        "interval_or_assign_or_custom": 1,
        "scan_interval": "0 4 * * *",
        "threads": 6,
        "run_scan_at_start_up": false,
        "movie_paths": [
            "/media/Movies/"
        ],
        "series_paths": [
            "/media/TV/",
            "/media/Anime/"
        ],
        "local_static_file_port": "19037"
    },
    "subtitle_sources": {
        "assrt_settings": {
            "enabled": false,
            "token": ""
        },
        "subtitle_best_settings": {
            "enabled": false,
            "api_key": ""
        }
    },
    "advanced_settings": {
        "proxy_settings": {
            "use_proxy": false,
            "use_which_proxy_protocol": "http",
            "local_http_proxy_server_port": "19036",
            "input_proxy_address": "127.0.0.1",
            "input_proxy_port": "10809",
            "need_pwd": false,
            "input_proxy_username": "",
            "input_proxy_password": ""
        },
        "tmdb_api_settings": {
            "enable": true,
            "api_key": "xxxxxx"
        },
        "debug_mode": true,
        "save_full_season_tmp_subtitles": false,
        "sub_type_priority": 0,
        "sub_name_formatter": 1,
        "save_multi_sub": false,
        "custom_video_exts": [
            ".ts"
        ],
        "fix_time_line": true,
        "topic": 1,
        "suppliers_settings": {
            "xunlei": {
                "name": "xunlei",
                "root_url": "http://sub.xmp.sandai.net:8000/subxl/%s.json",
                "search_url": "",
                "daily_download_limit": -1
            },
            "shooter": {
                "name": "shooter",
                "root_url": "https://www.shooter.cn/api/subapi.php",
                "search_url": "",
                "daily_download_limit": -1
            },
            "assrt": {
                "name": "assrt",
                "root_url": "https://api.assrt.net/v1",
                "search_url": "",
                "daily_download_limit": -1
            },
            "a4k": {
                "name": "a4k",
                "root_url": "https://www.a4k.net",
                "search_url": "/search?term=",
                "daily_download_limit": -1
            },
            "subhd": {
                "name": "subhd",
                "root_url": "https://subhd.tv",
                "search_url": "/search/%s",
                "daily_download_limit": 20
            },
            "zimuku": {
                "name": "zimuku",
                "root_url": "https://zimuku.org",
                "search_url": "/search?q=%s",
                "daily_download_limit": 20
            },
            "subtitle_best": {
                "name": "subtitle_best",
                "root_url": "https://api.subtitle.best/share-sub/v1",
                "search_url": "/search-movie",
                "daily_download_limit": -1
            }
        },
        "scan_logic": {
            "skip_chinese_movie": false,
            "skip_chinese_series": false
        },
        "task_queue": {
            "max_retry_times": 3,
            "one_job_time_out": 300,
            "interval": 10,
            "expiration_time": 90,
            "download_sub_during_x_days": 7,
            "one_sub_download_interval": 12,
            "check_pulic_ip_target_site": ""
        },
        "download_file_cache": {
            "ttl": 4320,
            "unit": "hour"
        }
    },
    "emby_settings": {
        "enable": false,
        "address_url": "xxxxxx",
        "api_key": "xxxxxx",
        "max_request_video_number": 500,
        "skip_watched": false,
        "movie_paths_mapping": {
            "/media/Movies/": ""
        },
        "series_paths_mapping": {
            "/media/Anime/": "",
            "/media/TV/": ""
        },
        "auto_or_manual": true,
        "threads": 6
    },
    "developer_settings": {
        "enable": false,
        "bark_server_address": ""
    },
    "timeline_fixer_settings": {
        "max_offset_time": 700,
        "min_offset": 0.2
    },
    "experimental_function": {
        "auto_change_sub_encode": {
            "enable": false,
            "des_encode_type": 0
        },
        "chs_cht_changer": {
            "enable": false,
            "des_chinese_language_type": 0
        },
        "remote_chrome_settings": {
            "enable": false,
            "remote_docker_url": "",
            "remote_adblock_path": "",
            "remote_user_data_dir": ""
        },
        "api_key_settings": {
            "enabled": true,
            "key": "xxxxx"
        },
        "local_chrome_settings": {
            "enabled": false,
            "local_chrome_exe_f_path": ""
        },
        "share_sub_settings": {
            "share_sub_enabled": true
        },
        "extend_log": {
            "SysLog": {
                "enable": false,
                "network": "",
                "address": "",
                "priority": 0,
                "tag": ""
            }
        }
    }
}

```
</details>

## 如果是使用 Docker，请给出对应的配置信息

<details><summary>展开/收起</summary>

```yaml
  # 字幕下载
  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest
    container_name: chinesesubfinder
    hostname: chinesesubfinder
    volumes:
      - /mnt/media_rw/e05559b0-0832-4a6c-8f41-10a159691716/.ugreen_nas/126527/nas/data/chinesesubfinder/browser:/root/.cache/rod/browser    # 容器重启后无需再次下载 chrome，除非 go-rod 更新
      - /mnt/media_rw/e05559b0-0832-4a6c-8f41-10a159691716/.ugreen_nas/126527/nas/data/chinesesubfinder/config:/config
      - /mnt/media_rw/e05559b0-0832-4a6c-8f41-10a159691716/.ugreen_nas/126527/nas/data/chinesesubfinder/SubFixCache:/app/SubFixCache
      - /mnt/media_rw/e05559b0-0832-4a6c-8f41-10a159691716/.ugreen_nas/126527/nas/home_cinema/media:/media
    environment:
      - PUID=1000         # uid
      - PGID=1000         # gid
      - PERMS=true        # 是否重设/media权限
      - TZ=Asia/Shanghai  # 时区
      - UMASK=000         # 权限掩码
    restart: unless-stopped
    network_mode: host
    # ports:
    #   - 19035:19035  # 从0.20.0版本开始，通过webui来设置
    #   - 19037:19037  # webui 的视频列表读取图片用，务必设置不要暴露到外网
    logging:
        driver: "json-file"
        options:
          max-size: "100m" # 限制docker控制台日志大小，可自行调整
```

</details>

## 给出媒体文件夹的目录结构

符合规范，被 tmm 刮削过。

## 请给出当次问题的完整日志

无相关日志

---

![image](https://user-images.githubusercontent.com/29500388/230739061-4d530467-5ddc-4c39-af9a-a5a940b87e02.png)

初步看了下 `/v1/video/list/one_series_subs` 返回的 `one_video_info` 为空。 

![image](https://user-images.githubusercontent.com/29500388/230739117-9bff648b-5a6b-43e4-8cc0-616d0707183d.png)

看起来是因为这部剧的视频格式比较特殊是 `.ts` , 不在支持的格式列表中。然后用户自定义格式的配置刚好未生效，setting 中的配置没有赋值给用到的变量(`_customVideoExts `)，就给忽略了。

![image](https://user-images.githubusercontent.com/29500388/230739132-3220948d-36d6-44f4-b4c3-c1614ea754ad.png)

https://github.com/ChineseSubFinder/ChineseSubFinder/blob/449f3681950bf20b569d86cb00adadf80187a3c7/pkg/util.go#L247-L249
