### ISSUE TITLE
希望能支持liunx软链接视频

### ISSUE THREAD

**Issue by saikishi** [ChineseSubFinder/ChineseSubFinder#754]
## 你使用的 chinesesubfinder 是什么版本，什么环境？

> chinesesubfinder 版本: v55.2
>
> 环境: Linux 群晖dms7.2
>
> 在程序运行日志头部或者 Web UI 可以看到

## 你遇到什么问题了？
不支持软链接

> 描述一下你遇到的问题
不支持软链接

## 你期望的结果

> 描述以下你期望的结果
希望能支持软链接，用cd2挂载的网盘，生成的视频软链接。群晖系统不可见，win系统可见。在win系统可以下载搜索字幕。

**Comment by Toretto5060** [comment]
我也遇到相同情况，场景为nastools整理后的路径，无法显示影片海报

**Comment by nrjycyd** [comment]
我是rclone挂载阿里云到群晖本地，软链接到媒体库刮削，我似乎找到上述软链接不能下载字幕的解决办法了。
compose配置



```
version: "3"
services:
  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest
    volumes:
      - /volume1/docker/chinesesubfinder/config:/config  # 冒号左边请修改为你想在主机上保存配置、日志等文件的路径
      - /volume2/video:/media   #软链接媒体库
      - /volume2/aliyun:/volume2/aliyun  #rclone挂载目录
      - /volume1/docker/chinesesubfinder/browser:/root/.cache/rod/browser    # 容器重启后无需再次下载 chrome，除非 go-rod 更新
    environment:
      - PUID=1026         # uid
      - PGID=100          # gid
      - PERMS=true        # 是否重设/media权限
      - TZ=Asia/Shanghai  # 时区
      - UMASK=022         # 权限掩码
    restart: always
    network_mode: bridge
    hostname: chinesesubfinder
    container_name: chinesesubfinder
    ports:
      - 19035:19035  # 从0.20.0版本开始，通过webui来设置
      - 19037:19037  # webui 的视频列表读取图片用，务必设置不要暴露到外网
    logging:
        driver: "json-file"
        options:
          max-size: "50m" # 限制docker控制台日志大小，可自行调整
```

效果图如下

![Snipaste_2024-06-29_21-19-14](https://github.com/ChineseSubFinder/ChineseSubFinder/assets/77444933/2768752a-568f-4a8c-ab04-3339589a6782)
![Snipaste_2024-06-29_21-20-13](https://github.com/ChineseSubFinder/ChineseSubFinder/assets/77444933/a56669f0-6819-43f6-b13c-e10b64656329)
![Snipaste_2024-06-29_21-19-40](https://github.com/ChineseSubFinder/ChineseSubFinder/assets/77444933/f3c0c225-3269-4fe5-a587-e9db9906a459)
![Snipaste_2024-06-29_21-21-09](https://github.com/ChineseSubFinder/ChineseSubFinder/assets/77444933/2a9ce8be-d5ce-4afa-acfb-2d1a3069f619)
